title: Digital Artifacts
description: a repository of media fragments and digital experimentation
twitter_site:
twitter_creator:
twitter_image_src: /assets/images/your_twitter_card_image.jpg
og_image: /assets/images/your_twitter_card_image.jpg
